//! 16×16 tray sprites + RGBA rasterizer for live tray icon updates.
//! `#` and `@` → opaque white; `.` → transparent.
//! macOS uses alpha as template mask; Windows shows the white pixels directly.
//!
//! Wired 2026-08-19 (§3.3.5 ①): D_TRAY_ALERT + rasterizer feed the live
//! retry-streak tray state. The evolution-stage sprites (egg→elder) were
//! dropped from the tray by the v4 redesign but are retained as assets for
//! future state variants — hence the module-level allow.
#![allow(dead_code)]

const D_TRAY_EGG: &str = "
................
................
......####......
.....######.....
.....######.....
....########....
....########....
....########....
....########....
....########....
....########....
.....######.....
.....######.....
......####......
................
................
";

const D_TRAY_BABY: &str = "
................
.......#........
......##........
......##........
.....#####......
....#######.....
...##.###.##....
...##.###.##....
...#########....
...#########....
....#######.....
....##...##.....
....##...##.....
.....#...#......
................
................
";

const D_TRAY_TEEN: &str = "
................
.......##.......
......####......
.......#........
......###.......
.....#####......
....#######.....
...##.###.##....
...##.###.##....
...#########....
...#########....
....#######.....
....##...##.....
....##...##.....
.....#...#......
................
";

const D_TRAY_ADULT: &str = "
................
....#.....#.....
....##...##.....
....##...##.....
.....#####......
....#######.....
...#########....
..##.#####.##...
..##.#####.##...
..###########...
..###########...
...#########....
...##.....##....
...##.....##....
....#.....#.....
................
";

const D_TRAY_ELDER: &str = "
................
....#.....#.....
.##.##...##.##..
..####...####...
.....#####......
....#######.....
...#########....
..###########...
..##.#####.##...
..##.#####.##...
..###########...
...#########....
...##.....##....
...##.....##....
....#.....#.....
................
";

pub(crate) const D_TRAY_ALERT: &str = "
@..............@
................
......####......
.....##.@##.....
....##.....##...
...##.@@@@@.##..
...##.@.@.@.##..
....##.@@@.##...
.....##...##....
......#####.....
.......###......
................
@..............@
................
@..............@
................
";

pub fn sprite_for_stage(stage: &str) -> &'static str {
    match stage {
        "egg" => D_TRAY_EGG,
        "baby" => D_TRAY_BABY,
        "teen" => D_TRAY_TEEN,
        "adult" => D_TRAY_ADULT,
        "elder" => D_TRAY_ELDER,
        _ => D_TRAY_EGG,
    }
}

/// Convert a sprite string into a 16×16 RGBA buffer.
pub fn sprite_to_rgba(sprite: &str) -> (Vec<u8>, u32, u32) {
    let lines: Vec<&str> = sprite.trim_matches('\n').lines().collect();
    let h = lines.len().max(1) as u32;
    let w = lines.iter().map(|l| l.chars().count()).max().unwrap_or(16) as u32;
    let mut buf = Vec::with_capacity((w * h * 4) as usize);
    for line in &lines {
        let chars: Vec<char> = line.chars().collect();
        for x in 0..w as usize {
            let ch = chars.get(x).copied().unwrap_or('.');
            if ch == '#' || ch == '@' {
                buf.extend_from_slice(&[255, 255, 255, 255]);
            } else {
                buf.extend_from_slice(&[0, 0, 0, 0]);
            }
        }
    }
    (buf, w, h)
}

/// Pick the sprite for current state. Alert variant when hunger is high.
pub fn sprite_for_state(stage: &str, hunger: i32) -> &'static str {
    if hunger >= 85 {
        return D_TRAY_ALERT;
    }
    sprite_for_stage(stage)
}
